name: minimal_calicost
channels:
  - bioconda
  - conda-forge
  - defaults
  - schmidt73
dependencies:
  - conda-libmamba-solver
  - bzip2
  - startle
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scanpy
  - anndata
  - numba
  - tqdm
  - statsmodels
  - networkx
  - pysam
  - ete3
  
